name: Demo

on:
  push:
    branches:
      - main

jobs:
  # 1. تست
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  # 2. بیلد + آپلود Artifact
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4

        with:
          name: dist-files
          path: dist
            
  # 3. دانلود Artifact و Deploy
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          
      - name: Output contents
        run: ls    

      - name: Deploy to server
        run: |
          echo "Deploying files..."
          # اینجا دستور واقعی deploy رو قرار بده
          # مثلا scp یا rsync برای کپی روی سرور
